### ISSUE TITLE
1.12.2 version erasing backpack content when going into creative

### ISSUE THREAD

**Issue by choekstr** [Shadows-of-Fire/ComPatchedStorage#8] opened 2020-01-19 16:41 UTC
Pack: E2E 1.75
forge: 14.23.5.2847
Compatched: 1.6.0
CompactStorage: 3.1-12
SSP/SMP: SMP linux server, windows client

I have a max sized backpack with tools, backup armor, etc.  Whenever I switch to creative the inventory in the backpack is cleared (lost).  This has happened twice now and doesn't come back with a relogin or a restart; meaning not a visual glitch or a desync issue.  I have had to restore from backup each time.

I personally can replicate this every time but not sure if it's my combination of mods, the color/size of backpack, or if this can be replicated.  Of course there is no crashlog, the console shows nothing relevant, just going into created, me realizing I have no tools, logging off and shutting down the server to restore from backup:
![ScreenShot 20 01 19-10 40 AM](https://user-images.githubusercontent.com/161085/72684653-29e4d200-3aa8-11ea-8336-c173b3b493c0.PNG)

Hoping this can be looked at with minimal details to go on.  Is there anything else I can provide?  I am so happy you have patched my favorite chest/backpack mod and would love this to not be an issue for others.

**Comment by Shadows-of-Fire** [comment] 2020-01-19 16:50
This is a bug in how the creative inventory accepts thr clients itemstacks, and can't be fixed without re-enabling the nbt overload bug

**Closed as completed by Shadows-of-Fire** 2020-01-19 16:50 UTC

**Comment by choekstr** [comment] 2020-01-19 17:00
wait, because someone might put a large inventory in the backpack, it is set to clear all inventory when going into creative? 
If so, enderIO solves this by restricting anything with an inventory in another inventory (silly and harsh). Thermal solves this by restricting large inventories in their satchels/strongboxes.  The solution for compatched is just to wipe all the inventory when going into creative??

**Comment by Shadows-of-Fire** [comment] 2020-01-19 17:02
The issue is more complicated than that, and honestly I don't feel like typing it out rn

**Comment by grydian** [comment] 2020-02-10 15:13
I get this is a complex fix and not possible.  I am curious should we put the backpack in a chest before going creative and then get it when we are done being in creative to prevent item loss?

**Comment by choekstr** [comment] 2020-02-10 15:47
That's what I have to do now.  And of course restore from backup when it gets deleted cause I forgot to remove my backpack from my inventory.  

I just store it in another normal inventory like an AA crate which isn't overly panicked about the NBT overload issue.  Haven't tried something else like the Cyclic expanded inventory; that would be nice if this worked.  As we know EnderIO has recently said nothing that even smells like it has an inventory will get stored in dark armor so that won't be an option anymore but perhaps there are other things that can be stored on the person when going into creative that works around the compatched storage bug.
